version: '2.1'

services:
  dynamodb:
    image: dwmkerr/dynamodb
    expose:
      - 8000

  common:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /application
    volumes:
      - ./:/application
      - /application/node_modules

  application:
    extends: common
    env_file: .env
    environment:
      - NODE_ENV=development
    expose:
      - 8001
    ports:
      - 8001:8001
    links:
      - dynamodb
    depends_on:
      - dynamodb
    command: npm run start-dynamo-admin

  test-unit:
    extends: common
    environment:
      - NODE_ENV=test

